//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busquedas.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_DMsEntities : DbContext
    {
        public DB_DMsEntities()
            : base("name=DB_DMsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<CAT_Materiales_TotalRegistrosBuscados_Result> CAT_Materiales_TotalRegistrosBuscados(Nullable<bool> pManejaLotes, Nullable<bool> pActivo, Nullable<bool> pMigrarSAP, string pBusqueda)
        {
            var pManejaLotesParameter = pManejaLotes.HasValue ?
                new ObjectParameter("pManejaLotes", pManejaLotes) :
                new ObjectParameter("pManejaLotes", typeof(bool));
    
            var pActivoParameter = pActivo.HasValue ?
                new ObjectParameter("pActivo", pActivo) :
                new ObjectParameter("pActivo", typeof(bool));
    
            var pMigrarSAPParameter = pMigrarSAP.HasValue ?
                new ObjectParameter("pMigrarSAP", pMigrarSAP) :
                new ObjectParameter("pMigrarSAP", typeof(bool));
    
            var pBusquedaParameter = pBusqueda != null ?
                new ObjectParameter("pBusqueda", pBusqueda) :
                new ObjectParameter("pBusqueda", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CAT_Materiales_TotalRegistrosBuscados_Result>("CAT_Materiales_TotalRegistrosBuscados", pManejaLotesParameter, pActivoParameter, pMigrarSAPParameter, pBusquedaParameter);
        }
    
        public virtual ObjectResult<VW_CAT_MaterialesEquivalentesDescripcionLarga_Sel_Result> VW_CAT_MaterialesEquivalentesDescripcionLarga_Sel(Nullable<long> pIdMaterialSistema)
        {
            var pIdMaterialSistemaParameter = pIdMaterialSistema.HasValue ?
                new ObjectParameter("pIdMaterialSistema", pIdMaterialSistema) :
                new ObjectParameter("pIdMaterialSistema", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VW_CAT_MaterialesEquivalentesDescripcionLarga_Sel_Result>("VW_CAT_MaterialesEquivalentesDescripcionLarga_Sel", pIdMaterialSistemaParameter);
        }
    
        public virtual ObjectResult<CAT_Materiales_Sel_Result> CAT_Materiales_Sel(Nullable<bool> pManejaLotes, Nullable<bool> pActivo, Nullable<bool> pMigrarSAP, string pBusqueda, Nullable<int> pInicio, Nullable<int> pTamanioLote, string pOrden)
        {
            var pManejaLotesParameter = pManejaLotes.HasValue ?
                new ObjectParameter("pManejaLotes", pManejaLotes) :
                new ObjectParameter("pManejaLotes", typeof(bool));
    
            var pActivoParameter = pActivo.HasValue ?
                new ObjectParameter("pActivo", pActivo) :
                new ObjectParameter("pActivo", typeof(bool));
    
            var pMigrarSAPParameter = pMigrarSAP.HasValue ?
                new ObjectParameter("pMigrarSAP", pMigrarSAP) :
                new ObjectParameter("pMigrarSAP", typeof(bool));
    
            var pBusquedaParameter = pBusqueda != null ?
                new ObjectParameter("pBusqueda", pBusqueda) :
                new ObjectParameter("pBusqueda", typeof(string));
    
            var pInicioParameter = pInicio.HasValue ?
                new ObjectParameter("pInicio", pInicio) :
                new ObjectParameter("pInicio", typeof(int));
    
            var pTamanioLoteParameter = pTamanioLote.HasValue ?
                new ObjectParameter("pTamanioLote", pTamanioLote) :
                new ObjectParameter("pTamanioLote", typeof(int));
    
            var pOrdenParameter = pOrden != null ?
                new ObjectParameter("pOrden", pOrden) :
                new ObjectParameter("pOrden", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CAT_Materiales_Sel_Result>("CAT_Materiales_Sel", pManejaLotesParameter, pActivoParameter, pMigrarSAPParameter, pBusquedaParameter, pInicioParameter, pTamanioLoteParameter, pOrdenParameter);
        }
    }
}
