//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agrupaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agrupaciones()
        {
            this.CatalogoCampos = new HashSet<CatalogoCampos>();
        }
    
        public int IdAgrupacion { get; set; }
        public int IdCatalogo { get; set; }
        public string NombreAgrupacion { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Catalogos Catalogos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogoCampos> CatalogoCampos { get; set; }
    }
}
