//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CamposCatalogoReferencias
    {
        public long CatalogoCampoId { get; set; }
        public long CatalogoCampoIdRef { get; set; }
        public string UpdateRule { get; set; }
        public bool Activo { get; set; }
    
        public virtual CatalogoCampos CatalogoCampos { get; set; }
        public virtual CatalogoCampos CatalogoCamposFK { get; set; }
    }
}
