//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalogos()
        {
            this.Agrupaciones = new HashSet<Agrupaciones>();
            this.CatalogoCampos = new HashSet<CatalogoCampos>();
            this.CatalogoConsultas = new HashSet<CatalogoConsultas>();
        }
    
        public int IdCatalogo { get; set; }
        public int IdCategoria { get; set; }
        public string NombreCatalogo { get; set; }
        public string NombreFisico { get; set; }
        public bool TablaCreada { get; set; }
        public bool Referenciada { get; set; }
        public bool Activa { get; set; }
        public bool ListoParaCrear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agrupaciones> Agrupaciones { get; set; }
        public virtual CAT_Categoria CAT_Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogoCampos> CatalogoCampos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogoConsultas> CatalogoConsultas { get; set; }
    }
}
