//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoConsultas
    {
        public int IdCatalogoConsulta { get; set; }
        public int IdCatalogo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string ScriptExecute { get; set; }
        public bool Activo { get; set; }
    
        public virtual Catalogos Catalogos { get; set; }
    }
}
