//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelacionCatalogos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RelacionCatalogos()
        {
            this.RelacionCatalogoCampos = new HashSet<RelacionCatalogoCampos>();
        }
    
        public long IdRelacionCatalogo { get; set; }
        public int IdCatalogoPK { get; set; }
        public int IdCatalogoFK { get; set; }
        public bool Activo { get; set; }
        public string NombreRelacion { get; set; }
    
        public virtual Catalogos Catalogos { get; set; }
        public virtual Catalogos Catalogos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelacionCatalogoCampos> RelacionCatalogoCampos { get; set; }
    }
}
