//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DBComponents
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_DMComponentsEntities : DbContext
    {
        public DB_DMComponentsEntities()
            : base("name=DB_DMComponentsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANKAZ_0001> ANKAZ_0001 { get; set; }
        public virtual DbSet<PT006> PT006 { get; set; }
        public virtual DbSet<RQSKT> RQSKT { get; set; }
        public virtual DbSet<SKAT> SKAT { get; set; }
        public virtual DbSet<T001> T001 { get; set; }
        public virtual DbSet<T001L> T001L { get; set; }
        public virtual DbSet<T001W> T001W { get; set; }
        public virtual DbSet<T002> T002 { get; set; }
        public virtual DbSet<T003O> T003O { get; set; }
        public virtual DbSet<T005F> T005F { get; set; }
        public virtual DbSet<T005T> T005T { get; set; }
        public virtual DbSet<T006> T006 { get; set; }
        public virtual DbSet<T023> T023 { get; set; }
        public virtual DbSet<T035T> T035T { get; set; }
        public virtual DbSet<T042Z> T042Z { get; set; }
        public virtual DbSet<T047T> T047T { get; set; }
        public virtual DbSet<T090NAT> T090NAT { get; set; }
        public virtual DbSet<T093S> T093S { get; set; }
        public virtual DbSet<T134> T134 { get; set; }
        public virtual DbSet<T137> T137 { get; set; }
        public virtual DbSet<T151T> T151T { get; set; }
        public virtual DbSet<T171T> T171T { get; set; }
        public virtual DbSet<TB002> TB002 { get; set; }
        public virtual DbSet<TCURT> TCURT { get; set; }
        public virtual DbSet<TFKB> TFKB { get; set; }
        public virtual DbSet<TFKTAXNUMTYPE_C> TFKTAXNUMTYPE_C { get; set; }
        public virtual DbSet<TKA01> TKA01 { get; set; }
        public virtual DbSet<TKA05> TKA05 { get; set; }
        public virtual DbSet<TPART> TPART { get; set; }
        public virtual DbSet<TSPAT> TSPAT { get; set; }
        public virtual DbSet<TVGRT> TVGRT { get; set; }
        public virtual DbSet<TVKBT> TVKBT { get; set; }
        public virtual DbSet<TVKOT> TVKOT { get; set; }
        public virtual DbSet<TVTWT> TVTWT { get; set; }
        public virtual DbSet<TZONT> TZONT { get; set; }
        public virtual DbSet<V_134_K> V_134_K { get; set; }
        public virtual DbSet<T005H> T005H { get; set; }
    }
}
