//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DBComponents
{
    using System;
    using System.Collections.Generic;
    
    public partial class T001W
    {
        public string WERKS { get; set; }
        public string NAME1 { get; set; }
        public string BUKRS { get; set; }
    
        public virtual T001 T001 { get; set; }
    }
}
