//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DBComponents
{
    using System;
    using System.Collections.Generic;
    
    public partial class T151T
    {
        public string KDGRP { get; set; }
        public string KTEXT { get; set; }
    }
}
