//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DBComponents
{
    using System;
    using System.Collections.Generic;
    
    public partial class TZONT
    {
        public string LAND1 { get; set; }
        public string ZONE1 { get; set; }
        public string VTEXT { get; set; }
    
        public virtual T005T T005T { get; set; }
    }
}
